### ISSUE TITLE
During callback when issuing 307 redirect, use fully qualified location instead of relative location.

### ISSUE THREAD

**Issue by kudakeru** [datawire/ambassador-pro#6]
We have multiple services hosted behind a single Ambassador service, with multiple domain names. Currently the 307 redirect step returns a location that's a relative path based on the CALLBACK_URL host. If the Ambassador Pro callback handler instead preserved the origin domain, it would allow us to automatically get routed back to the original requesting service.

**Comment by neurot1cal** [comment]
@richarddli Any updates on this?

**Comment by richarddli** [comment]
@neurot1cal Jake told me that this was resolved by you guys with the latest version. Please reopen if this is not the case.

**Comment by kudakeru** [comment]
Ah, sorry, that's on me. I meant the intermittent 404 issue was resolved. Using the fully qualified location is a feature request. My mistake.

**Comment by richarddli** [comment]
@kudakeru Have you tested FQDN with the latest version? It should be working there. cc @gsagula

**Comment by gsagula** [comment]
@kudakeru quay.io/datawire/ambassador-pro:0.0.5 should support FQDN. Please, let me know if that works. Thanks!

**Comment by kudakeru** [comment]
We still have the same problem. A request to fonts-svc.dev.activedisclosure.com triggers an Auth0 interaction, and when the user gets redirected after successful auth, they get sent to console.dev.activedisclosure.com/callback because that's the CALLBACK_URL value. It doesn't appear to be possible to override the callback URL as part of a service's annotations, and Ambassador isn't preserving the domain.

**Comment by kudakeru** [comment]
We have it defined as a separate host in the policies file with the
following:

- host: "fonts-svc.dev.activedisclosure.com"
     path: /*
     public: false

**Comment by gsagula** [comment]
@kudakeru I'm still looking into this ^^^.

**Comment by gsagula** [comment]
@kudakeru Thank you for your patience. I was able to get the FQDN to work. We will have a new release tomorrow so you can try it out.

**Comment by nbkrause** [comment]
@kudakeru The fix has been released in the private repo `ambassador_pro`. We are switching Ambassador Pro releases to this repo so we can have control over who has access to the image as we have released ambassador-pro open-core to the public. To access the image, you will need to 
#### 1. Create the docker-registry secret
I sent the username and password to you over slack
#### 2. Tell the deployment to use this secret when pulling the image
```
    spec:
      serviceAccountName: ambassador-pro
      imagePullSecrets:
      - name: ambassador-pro-registry-credentials
```
#### 3. Pull from the private repo
```
        image: quay.io/datawire/ambassador_pro:auth-0.0.6
```

Reach out if you have any questions!
